### ISSUE TITLE
"gitdocs serve" and "gitdocs build" is not working

### ISSUE THREAD

**Issue by sharanraj124** [timberio/gitdocs#156]
I am trying to do `gitdocs serve` and `git build` on [timber docs](https://github.com/timberio/gitdocs). Both command is not working.

```
± |master ?:1 ✗| → gitdocs --version

❯ GitDocs v2.0.0-beta23

± |master ?:1 ✗| → node --version
v9.11.2
```

This is the output of `gitdocs build`

```
± |master ?:1 ✗| → gitdocs build


❯ Creating your documentation site
❯ Bundling the Javascript app
❯ [✓] Syntax loaded
❯ [✓] Static assets loaded
❯ Generated and hydrated manifest
❯ Rendering and outputting HTML pages
❯ TypeError: Cannot convert undefined or null to object
    at keys (<anonymous>)
    at Object.<anonymous> (/Users/apple/.nvm/versions/node/v9.11.2/lib/node_modules/gitdocs/node_modules/@timberio/ui/dist/helpers/system.js:54:17)
    at Module._compile (internal/modules/cjs/loader.js:654:30)
    at loader (/Users/apple/.nvm/versions/node/v9.11.2/lib/node_modules/gitdocs/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/apple/.nvm/versions/node/v9.11.2/lib/node_modules/gitdocs/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (internal/modules/cjs/loader.js:566:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:506:12)
    at Function.Module._load (internal/modules/cjs/loader.js:498:3)
    at Module.require (internal/modules/cjs/loader.js:598:17)
    at require (internal/modules/cjs/helpers.js:11:18)
    at Object.<anonymous> (/Users/apple/.nvm/versions/node/v9.11.2/lib/node_modules/gitdocs/node_modules/@timberio/ui/dist/helpers/index.js:54:16)
    at Module._compile (internal/modules/cjs/loader.js:654:30)
    at loader (/Users/apple/.nvm/versions/node/v9.11.2/lib/node_modules/gitdocs/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/apple/.nvm/versions/node/v9.11.2/lib/node_modules/gitdocs/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (internal/modules/cjs/loader.js:566:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:506:12)
```

The `gitdocs serve` does not show any error message, but when I access the localhost:8000, it shows blank page.

Could you help me to resolve the issue?

**Comment by zsherman** [comment]
@carkmorwin this is the same error you were getting, correct?

**Comment by carkmorwin** [comment]
@zsherman correct

**Comment by zsherman** [comment]
@jsonmaur could you look into this when you get the change?

**Comment by jsonmaur** [comment]
Looks like it's coming from Timber UI. @zsherman Did you recently publish a breaking change?

**Comment by zsherman** [comment]
It's possible, it's coming from clean-element but I don't think that changed...

**Comment by jsonmaur** [comment]
It's a problem with the updated version of `styled-system` you added [here](https://github.com/timberio/ui/commit/c12f1b804f770a291177e328713d7abb64bc4a84). It must have some breaking changes.

**Comment by sharanraj124** [comment]
Even though `gitdocs serve` command does not throw any error in the terminal, the page is not loading in the browser.  I see following error in the Chrome Developer console

```
W registered
Navigated to http://localhost:8000/
react-dom.development.js?61bb:17410 Download the React DevTools for a better development experience: https://fb.me/react-devtools
system.js?6e95:54 Uncaught TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at eval (system.js?6e95:54)
    at Object../node_modules/@timberio/ui/dist/helpers/system.js (main.c37d80f6012c23c5f9df.js:2208)
    at __webpack_require__ (main.c37d80f6012c23c5f9df.js:725)
    at fn (main.c37d80f6012c23c5f9df.js:102)
    at eval (index.js?3040:54)
    at Object../node_modules/@timberio/ui/dist/helpers/index.js (main.c37d80f6012c23c5f9df.js:2172)
    at __webpack_require__ (main.c37d80f6012c23c5f9df.js:725)
    at fn (main.c37d80f6012c23c5f9df.js:102)
    at eval (index.js?325c:17)
(anonymous) @ system.js?6e95:54
./node_modules/@timberio/ui/dist/helpers/system.js @ main.c37d80f6012c23c5f9df.js:2208
__webpack_require__ @ main.c37d80f6012c23c5f9df.js:725
fn @ main.c37d80f6012c23c5f9df.js:102
(anonymous) @ index.js?3040:54
./node_modules/@timberio/ui/dist/helpers/index.js @ main.c37d80f6012c23c5f9df.js:2172
__webpack_require__ @ main.c37d80f6012c23c5f9df.js:725
fn @ main.c37d80f6012c23c5f9df.js:102
(anonymous) @ index.js?325c:17
./node_modules/@timberio/ui/dist/index.js @ main.c37d80f6012c23c5f9df.js:2232
__webpack_require__ @ main.c37d80f6012c23c5f9df.js:725
fn @ main.c37d80f6012c23c5f9df.js:102
(anonymous) @ index.js?81e2:3
./themes/default/application/index.js @ main.c37d80f6012c23c5f9df.js:9598
__webpack_require__ @ main.c37d80f6012c23c5f9df.js:725
fn @ main.c37d80f6012c23c5f9df.js:102
(anonymous) @ index.js?bc25:9
./themes/default/index.js @ main.c37d80f6012c23c5f9df.js:9730
__webpack_require__ @ main.c37d80f6012c23c5f9df.js:725
fn @ main.c37d80f6012c23c5f9df.js:102
0 @ main.c37d80f6012c23c5f9df.js:10018
__webpack_require__ @ main.c37d80f6012c23c5f9df.js:725
(anonymous) @ main.c37d80f6012c23c5f9df.js:792
(anonymous) @ main.c37d80f6012c23c5f9df.js:795
client.js?fec9:92 [HMR] connected
```

**Comment by coconup** [comment]
any temporary workaround for this? the package is basically unusable atm

**Comment by coconup** [comment]
@zsherman thanks for the quick answer! It indeed works when pointing npm to the latest commit in GitHub:

`npm install -g git+https://github.com/timberio/gitdocs.git#fe785a0b32193e61b7e9ddd7cf1ff210ee8ab0dc`

I previously installed by running `npm install -g gitdocs` but I guess it's not yet pointing to the latest commit.

**Comment by zsherman** [comment]
great 👍

**Comment by nholden** [comment]
I'm still seeing a similar error to [this one](https://github.com/timberio/gitdocs/issues/156#issuecomment-407998818) in my Chrome devtools when I run `gitdocs serve` after a fresh `npm install -g gitdocs@next`. Taking a peek at the commit history, it looks like [the last version bump happened on July 20](https://github.com/timberio/gitdocs/commit/f2f668f30229a87787ef365d13e007a1b7cc9ce3) and [this fix happened on July 30](https://github.com/timberio/gitdocs/commit/fe785a0b32193e61b7e9ddd7cf1ff210ee8ab0dc).

Does it make sense to release a new version now?

**Comment by zsherman** [comment]
hey @nholden, for sure—I'll cut a new release now.
