### ISSUE TITLE
gitdocs serve fails with hydrate related exception

### ISSUE THREAD

**Issue by sargsyan** [timberio/gitdocs#164]
OS: macOS highSierra

Stacktrace:

```/usr/local/lib/node_modules/gitdocs/src/core/hydrate.js:20
  return { ...data, ...dataFromParent }
           ^^^

SyntaxError: Unexpected token ...
    at createScript (vm.js:74:10)
    at Object.runInThisContext (vm.js:116:10)
    at Module._compile (module.js:533:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/gitdocs/src/core/index.js:4:25)
```

**gitdocs init** works without problems

**Comment by sargsyan** [comment]
Seems that the problem was with nodejs. After updating **node** the issue has gone and **gitdocs serve** works
