### ISSUE TITLE
Command failed: cd node_modules/gitdocs && node_modules/react-static/bin/react-static start

### ISSUE THREAD

**Issue by tiptronic** [timberio/gitdocs#20]
Somethings (obviously) missing 😉 

Any idea?

Andy

`/usr/local/lib/node_modules/gitdocs/node_modules/yargs/yargs.js:1100
      else throw err
           ^

Error: Command failed: cd node_modules/gitdocs && node_modules/react-static/bin/react-static start
    at checkExecSyncError (child_process.js:601:13)
    at execSync (child_process.js:641:13)
    at Object.handler (/usr/local/lib/node_modules/gitdocs/bin/gitdocs.js:32:7)
    at Object.runCommand (/usr/local/lib/node_modules/gitdocs/node_modules/yargs/lib/command.js:228:22)
    at Object.parseArgs [as _parseArgs] (/usr/local/lib/node_modules/gitdocs/node_modules/yargs/yargs.js:1013:30)
    at Object.get [as argv] (/usr/local/lib/node_modules/gitdocs/node_modules/yargs/yargs.js:957:21)
    at Object.<anonymous> (/usr/local/lib/node_modules/gitdocs/bin/gitdocs.js:72:3)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)`

**Comment by zsherman** [comment]
@tiptronic could you tell me a bit about how you tried to start gitdocs? did you just run `gitdocs serve`?

**Comment by tiptronic** [comment]
Hi @zsherman of course, but I did barely nothing:

- npm i -g gitdocs
- gitdocs serve
there's just one 'docs' folder containing a bare 'readme.md' file in the cwd

I have a recent npm and node installed (5.6.0, 8.9.1)
It's a fairly clean OSX install (latest)...

while installing gitdocs using npm I already got this babel related error:

`npm WARN deprecated babel-preset-es2015@6.24.1: 🙌  Thanks for using Babel: we recommend using babel-preset-env now: please read babeljs.io/env to update!
npm WARN deprecated babel-preset-latest@6.24.1: We're super 😸  excited that you're trying to use ES2017+ syntax, but instead of making more yearly presets 😭 , Babel now has a better preset that we recommend you use instead: npm install babel-preset-env --save-dev. preset-env without options will compile ES2015+ down to ES5 just like using all the presets together and thus is more future proof. It also allows you to target specific browsers so that Babel can do less work and you can ship native ES2015+ to user 😎 ! We are also in the process of releasing v7, so please give http://babeljs.io/blog/2017/09/12/planning-for-7.0 a read and help test it out in beta! Thanks so much for using Babel 🙏, please give us a follow on Twitter @babeljs for news on Babel, join slack.babeljs.io for discussion/development and help support the project at opencollective.com/babel
npm WARN deprecated babel-preset-es2017@6.24.1: 🙌  Thanks for using Babel: we recommend using babel-preset-env now: please read babeljs.io/env to update!
npm WARN deprecated babel-preset-es2016@6.24.1: 🙌  Thanks for using Babel: we recommend using babel-preset-env now: please read babeljs.io/env to update!
/usr/local/bin/gitdocs -> /usr/local/lib/node_modules/gitdocs/bin/gitdocs.js
+ gitdocs@1.3.0`

If you need more info, just let me know

**Comment by etimberg** [comment]
I was seeing this locally too. For me, the `cd` caused a problem as that directory didn’t exist

**Comment by tiptronic** [comment]
which directory do you mean?  I haven't had time to check out everything - sorry...

**Comment by etimberg** [comment]
@tiptronic `/node_modules/gitdocs`. When I created that, it seemed to get further but I was testing a local build and not something installed from NPM.

I will try and reproduce this issue tomorrow and see what I can find

**Comment by tiptronic** [comment]
@etimberg I think the problem could be here (depending from where the code is executed):
 
`
cd node_modules/gitdocs && node_modules/react-static/bin/react-static start`

If this is executed in gitdoc's scope, there is no such thing as 'node_modules/gitdocs' inside gitdocs node_modules. 
If it is executed relative to the /usr/local/lib/, there is no such thing as react-static

Maybe it should be:

`
cd  /usr/local/lib/node_modules/gitdocs && /usr/local/lib/node_modules/gitdocs/node_modules/react-static/bin/react-static start` 
?

**Comment by etimberg** [comment]
@tiptronic if you're interested, give #23 a try

**Comment by tiptronic** [comment]
@etimberg 

- npm run build builds now to dist/
- built gitdocs still don't work from the file-system (file://) - the .md is removed and so it doesn't link (just tried it using 1 small readme.md in docs/)
- gitdocs serve still doesn't work, as there are now other dependencies missing (in npm), eg. 'is-global').

 I'll wait until the changes are merged and then try again
Did you ever try to run from a clean node-install?

**Comment by tiptronic** [comment]
@etimberg Here's a log, when I'm trying to run build on locally patched gitdocs (could also be I did something wrong, so don't rely on it 😊)

``` 0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'run', 'build' ]
2 info using npm@5.5.1
3 info using node@v8.9.3
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle gitdocs@1.3.0~prebuild: gitdocs@1.3.0
6 info lifecycle gitdocs@1.3.0~build: gitdocs@1.3.0
7 verbose lifecycle gitdocs@1.3.0~build: unsafe-perm in lifecycle true
8 verbose lifecycle gitdocs@1.3.0~build: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/Users/andy/Desktop/test/gitdocs/node_modules/.bin:/Library/Frameworks/Python.framework/Versions/3.6/bin:/Library/Frameworks/Python.framework/Versions/3.5/bin:/usr/local/sbin:/Library/Developer/Toolchains/swift-latest.xctoolchain/usr/bin:/Users/andy/.node/bin:/usr/local/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/andy/go/bin
9 verbose lifecycle gitdocs@1.3.0~build: CWD: /Users/andy/Desktop/test/gitdocs
10 silly lifecycle gitdocs@1.3.0~build: Args: [ '-c', 'react-static build' ]
11 silly lifecycle gitdocs@1.3.0~build: Returned: code: 1  signal: null
12 info lifecycle gitdocs@1.3.0~build: Failed to exec build script
13 verbose stack Error: gitdocs@1.3.0 build: `react-static build`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:280:16)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at EventEmitter.emit (events.js:214:7)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at ChildProcess.emit (events.js:214:7)
13 verbose stack     at maybeClose (internal/child_process.js:925:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
14 verbose pkgid gitdocs@1.3.0
15 verbose cwd /Users/andy/Desktop/test/gitdocs
16 verbose Darwin 17.3.0
17 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "build"
18 verbose node v8.9.3
19 verbose npm  v5.5.1
20 error code ELIFECYCLE
21 error errno 1
22 error gitdocs@1.3.0 build: `react-static build`
22 error Exit status 1
23 error Failed at the gitdocs@1.3.0 build script.
```

**Comment by etimberg** [comment]
@tiptronic thanks for the log. I'll give it a shot now and see if I can reproduce with a clean install.

For the `is-global` dependency I added it to `package.json` but forgot to update `yarn.lock` and `package-lock.json`. Both should be updated in master now. Simply removing those files and re-installing should ensure the dependency gets installed.

I was noticing problems when the file was named `readme.md` but when writing the init command in #24 last night, I found that other file names worked. I'll try and investigate the readme.md problems soon.

**Comment by etimberg** [comment]
Locally I have my synced version of `gitdocs` symlinked into the global node modules so that I can simulate the global CLI elsewhere. 

I synced the latest from `master`, deleted `node_modules` and then ran `yarn install`. 
In another directory I ran `gitdocs init` to create a test project and then `gitdocs serve`. Both were successful.

**Comment by tiptronic** [comment]
Hi @etimberg - interestingly uninstalling gitdocs completely and starting fresh (using a manual link to the repo) made it work (although I had no 'node_modules' when cloning the master-branch. 

It builds and serves fine (as long as there's no space in the filename... I'll open some issues for my findings separately.
Thx for your help!

**Comment by DavidAntaramian** [comment]
I think this issue still stands. I've attempted to create a basic gitdocs site, and I keep running into the same failure with `yargs`.

OS: macOS Sierra (10.12.6)
Node: 8.9.1
Yarn: 1.3.2
Gitdocs: 1.3.2 _and_ 75e9fee5c8ef5aa34e0629492d540a1e0f9df2f9

*Steps to reproduce:*

  1. Create a new directory: `mkdir gitdocs_testing`
  2. Enter the new directory: `cd gitdocs_testing`
  3. Initialize a new project, accepting defaults: `yarn init`
  4. Add `gitdocs` as a development-only dependency: `yarn add gitdocs --dev`
  5. Initialize a new `gitdocs` project, accepting defaults: `yarn gitdocs init`
  6. Try to serve a local copy of the project: `yarn gitdocs serve`

*Expected:*

An HTTP service is started providing a compiled-and-watched version of the gitdocs project.

*Actual:*

Command fails with exit code `1` and the following output:

```
yarn run v1.3.2
$ /Users/david/Code/timber.io/tmp/gitdocs_testing/node_modules/.bin/gitdocs serve
No path specified. Falling back to react-static dev server.
/Users/david/Code/timber.io/tmp/gitdocs_testing/node_modules/yargs/yargs.js:1100
      else throw err
           ^

Error: Command failed: /Users/david/Code/timber.io/tmp/gitdocs_testing/node_modules/gitdocs/node_modules/react-static/bin/react-static start
    at checkExecSyncError (child_process.js:601:13)
    at execSync (child_process.js:641:13)
    at Object.handler (/Users/david/Code/timber.io/tmp/gitdocs_testing/node_modules/gitdocs/bin/gitdocs.js:73:9)
    at Object.runCommand (/Users/david/Code/timber.io/tmp/gitdocs_testing/node_modules/yargs/lib/command.js:235:44)
    at Object.parseArgs [as _parseArgs] (/Users/david/Code/timber.io/tmp/gitdocs_testing/node_modules/yargs/yargs.js:1013:30)
    at Object.get [as argv] (/Users/david/Code/timber.io/tmp/gitdocs_testing/node_modules/yargs/yargs.js:957:21)
    at Object.<anonymous> (/Users/david/Code/timber.io/tmp/gitdocs_testing/node_modules/gitdocs/bin/gitdocs.js:240:3)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

Recording of the bug using Asciinema:

[![Terminal session recorded using Asciinema showing the bug](https://asciinema.org/a/itzowMEyHJdGzV5H96SXiuvD3.png)](https://asciinema.org/a/itzowMEyHJdGzV5H96SXiuvD3)

**Comment by zsherman** [comment]
Just released `1.4.0`, let me know if that solves things.

**Comment by DavidAntaramian** [comment]
`1.4.0` does not solve this issue; the behavior is the same as above.
